(function(){
'use strict';
var TABS=['總覽','技術分析','基本面','籌碼分析','財務分析','產業分析','波浪分析','AI 選股流程','歷史推薦','預測追蹤','相關新聞'];
var KEYS=['overview','technical','fundamental','chips','financial','industry','wave','engine','history','prediction','news'];
var S={symbol:'',market:'TWSE',daily:[],funds:[],recs:[],corp:[]};
function q(s){return document.querySelector(s)}
function e(v){return String(v==null?'—':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function n(v,d){var x=Number(v);return Number.isFinite(x)?x.toFixed(d==null?2:d):'—'}
function pct(v,d){var x=Number(v);return Number.isFinite(x)?(x>=0?'+':'')+x.toFixed(d==null?1:d)+'%':'—'}
function token(){try{return JSON.parse(localStorage.getItem('sad_auth_session_v1')||'{}').accessToken||''}catch(_){return ''}}
function get(path){return fetch(window.APP_CONFIG.SUPABASE_URL+'/rest/v1/'+path,{headers:{apikey:window.APP_CONFIG.SUPABASE_ANON_KEY,Authorization:'Bearer '+(token()||window.APP_CONFIG.SUPABASE_ANON_KEY)}}).then(function(r){if(!r.ok)throw Error(String(r.status));return r.json()})}
function root(){var r=q('#analysis-tab-content');if(!r){var tabs=q('.stock-tabs');if(!tabs)return null;r=document.createElement('section');r.id='analysis-tab-content';r.className='stock-panel analysis-tab-root';tabs.parentNode.insertBefore(r,tabs.nextSibling)}return r}
function chart(rows){if(!rows.length)return '<div class="stock-empty">尚無可驗證歷史行情資料。</div>';var w=900,h=300,p=28,min=Infinity,max=-Infinity;rows.forEach(function(r){min=Math.min(min,Number(r.low));max=Math.max(max,Number(r.high))});var range=max-min||1,out='<svg viewBox="0 0 '+w+' '+h+'" preserveAspectRatio="none" aria-label="日線 K 線">';rows.forEach(function(r,i){var x=p+i/(Math.max(rows.length-1,1))*(w-2*p),yo=h-p-(Number(r.open)-min)/range*(h-2*p),yc=h-p-(Number(r.close)-min)/range*(h-2*p),yh=h-p-(Number(r.high)-min)/range*(h-2*p),yl=h-p-(Number(r.low)-min)/range*(h-2*p),up=Number(r.close)>=Number(r.open),c=up?'#13a878':'#ef4444',bw=Math.max(3,Math.min(10,(w-2*p)/rows.length*.65)),top=Math.min(yo,yc),bh=Math.max(2,Math.abs(yo-yc));out+='<line x1="'+x+'" x2="'+x+'" y1="'+yh+'" y2="'+yl+'" stroke="'+c+'" stroke-width="1.5"/><rect x="'+(x-bw/2)+'" y="'+top+'" width="'+bw+'" height="'+bh+'" fill="'+c+'"/>'});return out+'</svg>'}
function table(rows,head){var s='<table class="stock-table">';if(head){s+='<thead><tr>';head.forEach(function(x){s+='<th>'+e(x)+'</th>'});s+='</tr></thead>'}s+='<tbody>';rows.forEach(function(r){s+='<tr>';r.forEach(function(x){s+='<td>'+e(x)+'</td>'});s+='</tr>'});return s+'</tbody></table>'}
function overview(){var l=S.daily[S.daily.length-1],p=S.daily[S.daily.length-2],ch=l&&p?Number(l.close)-Number(p.close):null,cp=ch!=null&&Number(p.close)?ch/Number(p.close)*100:null;return '<div class="analysis-tab-grid two"><section><h3>K 線走勢</h3><p class="stock-panel-sub">Production OHLCV；本區只呈現真正 K 線。</p><div class="analysis-chart">'+chart(S.daily.slice(-60))+'</div></section><section><h3>最新行情</h3>'+table([['日期',l&&l.trading_date],['開盤',l&&n(l.open)],['最高',l&&n(l.high)],['最低',l&&n(l.low)],['收盤',l&&n(l.close)],['漲跌',ch==null?'—':n(ch)+' ('+pct(cp,2)+')'],['成交量',l&&Number(l.volume).toLocaleString('en-US')],['資料來源',l&&l.source]])+'</section></div><section><h3>資料狀態</h3><p class="stock-empty">'+(S.daily.length?'已載入 '+S.daily.length+' 筆 Production 日線資料，最新交易日 '+e(l.trading_date)+'。':'尚無可驗證資料。')+'</p></section>'}
function rsi(rows,p){if(rows.length<=p)return null;var g=0,l=0,i,d;for(i=1;i<=p;i++){d=Number(rows[i].close)-Number(rows[i-1].close);if(d>=0)g+=d;else l-=d}var ag=g/p,al=l/p;for(i=p+1;i<rows.length;i++){d=Number(rows[i].close)-Number(rows[i-1].close);ag=(ag*(p-1)+Math.max(d,0))/p;al=(al*(p-1)+Math.max(-d,0))/p}return al===0?100:100-100/(1+ag/al)}
function ema(a,p){if(a.length<p)return null;var x=a.slice(0,p).reduce(function(s,v){return s+v},0)/p,k=2/(p+1);for(var i=p;i<a.length;i++)x=a[i]*k+x*(1-k);return x}
function technical(){var a=S.daily.map(function(r){return Number(r.close)}).filter(Number.isFinite),last=S.daily[S.daily.length-1],R=rsi(S.daily,14),E12=ema(a,12),E26=ema(a,26),M=E12!=null&&E26!=null?E12-E26:null,t=S.daily.slice(-20),avg=t.length?t.reduce(function(s,r){return s+Number(r.close)},0)/t.length:null,sd=t.length?Math.sqrt(t.reduce(function(s,r){return s+Math.pow(Number(r.close)-avg,2)},0)/t.length):null;return '<div class="analysis-tab-grid two"><section><h3>K 線技術圖</h3><p class="stock-panel-sub">以 Production OHLCV 計算；公式結果可由原始日線重算。</p><div class="analysis-chart">'+chart(S.daily.slice(-90))+'</div></section><section><h3>技術指標</h3>'+table([['RSI (14)',n(R,1),R==null?'待驗證':R>=70?'偏高':R<=30?'偏低':'中性'],['MACD (12,26)',n(M,2),M==null?'待驗證':M>=0?'正值':'負值'],['MA20',n(avg),avg==null?'待驗證':'可驗證'],['布林上軌',n(avg!=null&&sd!=null?avg+2*sd:null)],['布林下軌',n(avg!=null&&sd!=null?avg-2*sd:null)],['最新收盤',n(last&&last.close)]])+'</section></div><section><h3>近期日線資料</h3>'+table(S.daily.slice(-20).reverse().map(function(r){return [r.trading_date,n(r.open),n(r.high),n(r.low),n(r.close),Number(r.volume).toLocaleString('en-US')] }),['日期','開盤','最高','最低','收盤','成交量'])+'</section>'}
function fundamental(){var f=S.funds[0],l=S.daily[S.daily.length-1],per=f&&f.eps&&l?Number(l.close)/Number(f.eps):null,pbr=f&&f.book_value_per_share&&l?Number(l.close)/Number(f.book_value_per_share):null;return '<section><h3>基本面重點</h3>'+table([['報告期間',f&&f.reporting_period],['EPS',f&&n(f.eps)],['本益比',per==null?'資料不足':n(per)],['股價淨值比',pbr==null?'資料不足':n(pbr)],['每股股利',f&&n(f.dividend_per_share)],['營收',f&&n(f.revenue)],['淨利',f&&n(f.net_income)],['股東權益',f&&n(f.equity)],['資料來源',f&&f.source]])+'</section><section><h3>歷期基本面</h3>'+table(S.funds.map(function(x){return [x.reporting_period,n(x.eps),n(x.revenue),n(x.net_income),n(x.equity),n(x.book_value_per_share)]}),['期間','EPS','營收','淨利','股東權益','每股淨值'])+'</section>'}
function chips(){return '<section><h3>籌碼分析</h3><p class="stock-empty">Production 目前沒有三大法人、融資融券或主力分點欄位，本區不產生推測值。</p>'+table([['可驗證籌碼資料','目前無'],['公司行動紀錄',String(S.corp.length)+' 筆'],['說明','corporate_actions 不等同籌碼指標']])+'</section>'}
function financial(){return '<section><h3>財務趨勢</h3><p class="stock-panel-sub">Production fundamentals 歷期資料，不以缺漏期間插值。</p>'+table(S.funds.map(function(x){return [x.reporting_period,n(x.revenue),n(x.net_income),n(x.eps),n(x.equity)]}),['期間','營收','淨利','EPS','股東權益'])+'</section>'}
function industry(){return '<section><h3>產業分析</h3><p class="stock-empty">目前 Production fundamentals 未提供獨立產業分類欄位；不以模型猜測。</p>'+table([['公司',q('#analysis-name-display')&&q('#analysis-name-display').textContent],['市場',S.market],['財務紀錄',String(S.funds.length)+' 筆']])+'</section>'}
function wave(){var a=S.daily.slice(-60),c=a.map(function(r){return Number(r.close)}).filter(Number.isFinite);if(c.length<10)return '<section><h3>波浪分析</h3><p class="stock-empty">連續日線資料不足。</p></section>';return '<div class="analysis-tab-grid two"><section><h3>價格波段</h3><div class="analysis-chart">'+chart(a)+'</div></section><section><h3>客觀區間摘要</h3>'+table([['60日區間報酬',pct((c[c.length-1]-c[0])/c[0]*100,2)],['區間最高',n(Math.max.apply(null,c))],['區間最低',n(Math.min.apply(null,c))],['最新收盤',n(c[c.length-1])],['方法','價格序列描述；非主觀波浪判讀']])+'</section></div>'}
function engine(){var r=S.recs[0],b=r&&r.score_breakdown;return '<div class="analysis-tab-grid two"><section><h3>AI 選股流程</h3>'+table([['推薦狀態',r&&r.decision_state],['AI Score',r&&n(r.recommendation_score,0)],['排名',r&&r.rank],['資料狀態',r&&r.data_status],['Evidence Strength',r&&r.evidence_strength],['Calculation Version',r&&r.calculation_version]])+'</section><section><h3>評分拆解</h3>'+(b?table([['Fundamental',n(b.fundamental&&b.fundamental.score,1)],['Fundamental weight',pct(Number(b.fundamental&&b.fundamental.weight)*100,0)],['Technical',n(b.technical&&b.technical.score,1)],['Technical weight',pct(Number(b.technical&&b.technical.weight)*100,0)],['Composite',n(b.composite_score,1)] ]):'<p class="stock-empty">尚無 score_breakdown。</p>')+'</section></div><section><h3>推薦理由</h3><ul class="stock-reason">'+((r&&r.recommendation_reason)||[]).map(function(x){return '<li>'+e(x)+'</li>'}).join('')+'</ul></section>'}
function history(){return '<section><h3>歷史推薦</h3>'+table(S.recs.map(function(r){return [r.calculation_date,r.rank,r.decision_state,n(r.recommendation_score,0),n(r.reference_price),n(r.target_price),pct(r.expected_return_pct),r.data_as_of]}),['計算日','排名','狀態','Score','參考價','目標價','預期報酬','資料日'])+'</section>'}
function prediction(){var r=S.recs[0],l=S.daily[S.daily.length-1];return '<div class="analysis-tab-grid two"><section><h3>預測追蹤</h3>'+table([['推薦計算日',r&&r.calculation_date],['資料基準日',r&&r.data_as_of],['參考價',r&&n(r.reference_price)],['目標價',r&&n(r.target_price)],['預期報酬',r&&pct(r.expected_return_pct)],['實際最新收盤',l&&n(l.close)]])+'</section><section><h3>預測成熟度</h3><p class="stock-empty">預測準確率需等待成熟樣本，不以未成熟資料代替勝率。</p></section></div>'}
function news(){return '<section><h3>相關新聞</h3><p class="stock-empty">Production 尚未接入可驗證新聞來源，不顯示外部或模型生成新聞。</p></section>'}
var V={overview:overview,technical:technical,fundamental:fundamental,chips:chips,financial:financial,industry:industry,wave:wave,engine:engine,history:history,prediction:prediction,news:news};
function render(k){var r=root();if(!r)return;r.innerHTML=V[k]?V[k]():'';r.dataset.tab=k}
function setTab(i){document.querySelectorAll('.stock-tab').forEach(function(t,j){t.classList.toggle('active',i===j);t.setAttribute('aria-selected',i===j?'true':'false')});render(KEYS[i]||'overview')}
function load(){var sym=(q('#analysis-symbol')&&q('#analysis-symbol').value.trim())||(q('#analysis-symbol-display')&&q('#analysis-symbol-display').textContent.trim());if(!sym)return;S.symbol=sym.toUpperCase().replace(/\s.*$/,'');S.market=(q('#analysis-market-display')&&q('#analysis-market-display').textContent.trim())||'TWSE';var x=encodeURIComponent(S.symbol),m=encodeURIComponent(S.market),since=new Date(Date.now()-365*86400000).toISOString().slice(0,10);Promise.allSettled([get('market_daily?symbol=eq.'+x+'&market=eq.'+m+'&trading_date=gte.'+since+'&order=trading_date.asc'),get('fundamentals?symbol=eq.'+x+'&market=eq.'+m+'&order=reporting_period.desc&limit=12'),get('market_top50?symbol=eq.'+x+'&market=eq.'+m+'&order=calculation_date.desc&limit=30'),get('corporate_actions?symbol=eq.'+x+'&market=eq.'+m+'&order=effective_date.desc&limit=30')]).then(function(a){S.daily=a[0].status==='fulfilled'?a[0].value:[];S.funds=a[1].status==='fulfilled'?a[1].value:[];S.recs=a[2].status==='fulfilled'?a[2].value:[];S.corp=a[3].status==='fulfilled'?a[3].value:[];render(q('#analysis-tab-content')&&q('#analysis-tab-content').dataset.tab||'overview')})}
function wire(){var tabs=document.querySelectorAll('.stock-tab');if(!tabs.length)return false;tabs.forEach(function(t,i){t.type='button';t.onclick=function(ev){ev.preventDefault();setTab(i)}});var s=q('#analysis-search');if(s&&!s.dataset.tabsV2){s.dataset.tabsV2='1';s.addEventListener('click',function(){setTimeout(load,600)})}return true}
function boot(){if(!wire()){setTimeout(boot,300);return}setTab(0);setTimeout(load,900)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.StockAnalysisTabsV2={load:load,setTab:function(name){var i=KEYS.indexOf(name);if(i>=0)setTab(i)}};
})();
